# Generated by Django 4.0.2 on 2022-02-22 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usellshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('discount', models.CharField(max_length=130)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usellshop.course')),
            ],
        ),
    ]
